"""empty message

Revision ID: 2b4afe2fdb1f
Revises: ce913c77a373
Create Date: 2021-02-23 23:11:55.522729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b4afe2fdb1f'
down_revision = 'ce913c77a373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('timestamp', sa.Float(), nullable=True))
    op.drop_column('sound', 'dat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('dat', mysql.FLOAT(), nullable=True))
    op.drop_column('sound', 'timestamp')
    # ### end Alembic commands ###
