"""empty message

Revision ID: ce913c77a373
Revises: ca2a0d2d112f
Create Date: 2021-02-23 22:56:56.987220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce913c77a373'
down_revision = 'ca2a0d2d112f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('dat', sa.Float(), nullable=True))
    op.drop_column('sound', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('date', mysql.FLOAT(), nullable=True))
    op.drop_column('sound', 'dat')
    # ### end Alembic commands ###
