"""empty message

Revision ID: e641795f7b8d
Revises: 2b4afe2fdb1f
Create Date: 2021-02-23 23:22:42.729933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e641795f7b8d'
down_revision = '2b4afe2fdb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('date', sa.Float(), nullable=True))
    op.drop_column('sound', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sound', sa.Column('timestamp', mysql.FLOAT(), nullable=True))
    op.drop_column('sound', 'date')
    # ### end Alembic commands ###
