version: '3.7'

networks:
  net1:
    name: net1

services:
  mysql:
    container_name: mysql
    build:
        context: ./db 
    restart: unless-stopped
    networks:
        - net1
    volumes:
        - ./dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx    
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  app:
    container_name: app
    ports:
        - 54322:5000
    build:
        context: ./app 
    restart: unless-stopped
    networks:
        - net1
    links:
        - mysql
    volumes:
        - ./app:/pfg
    depends_on: 
        - mysql
    
volumes:
    dbdata: