version: '3.7'
networks:
    net2:
        name: net2

services:

    prod:
        container_name: prod
        ports:
            - 54321:5000
        build:
            context: ./prod
        restart: unless-stopped
        networks:
            - net2

    broker:
        container_name: broker
        build:
            context: ./broker
        restart: unless-stopped
        networks:
            - net2   
